### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mshaugh** [Carberra/Carberretta#10]
# Logging

**Features**

* Member nickname changes
    * Old nickname
    * New nickname
* Member role additions and removals
    * Role that was added/removed
    * Perhaps the total number of roles
* User avatar changes
    * Old avatar (as thumbnail)
    * New avatar (as image)
* Message edits
    * Author
    * Old content
    * New content
    * Include attachments, media, etc.
* Message deletions
    * Author
    * Content
    * Deleted by (via audit log)
    * Include attachments, media, etc.

**Comment by JohnnyJTH** [comment]
I'll do it

**Comment by JohnnyJTH** [comment]
https://github.com/Carberra/Carberretta/pull/92
