### ISSUE TITLE
RSS feed cache causing delays in youtube announcements

### ISSUE THREAD

**Issue by Jonxslays** [Carberra/Carberretta#100]
There doesn't seem to be a way to circumvent the caching of the feed. I am looking into other options for obtaining the youtube video ID's likely via web scraping.

**Comment by mshaugh** [comment]
What's wrong with https://developers.google.com/youtube/v3/guides/push_notifications?

**Comment by Jonxslays** [comment]
I finally have a working implementation of the server running within the bot. This should be coming soon.
