### ISSUE TITLE
format -> fstrings

### ISSUE THREAD

**Issue by IkBenOlie5** [Carberra/Carberretta#102]
format can be changed in utils/string.py and in bot/cogs/meta.py (this one is in triple quotes tho)

**Comment by parafoxia** [comment]
Can you show specifically where you mean?

**Comment by ZestyBlaze** [comment]
It's the same change I made in my PR for Modmail

**Comment by IkBenOlie5** [comment]
String.py:37
Meta.py:165

**Comment by IkBenOlie5** [comment]
I can do this one if you want
