### ISSUE TITLE
Add Suggestion Command

### ISSUE THREAD

**Issue by JohnnyJTH** [Carberra/Carberretta#103]
Add a `+suggest` command specifically for the #feedback channel to see if people like the idea or not on a voting level.

**Comment by JohnnyJTH** [comment]
If helish does not want to, I'll do it.

**Comment by helish88** [comment]
I'll do.

**Comment by parafoxia** [comment]
I'll give it to helish seen as you've still got the logging to finish off Johnny lmao.

**Comment by JohnnyJTH** [comment]
> I'll give it to helish seen as you've still got the logging to finish off Johnny lmao.

yeye I wanted helish to do it. Just incase he didn't, it's easy to do.

**Comment by parafoxia** [comment]
Fairs

**Comment by parafoxia** [comment]
I'm gonna put this on discussion right now, and we'll see what idea helish has for it.

**Comment by JohnnyJTH** [comment]
Well isn't it just a command (+suggest), you'll execute it in either the channel itself and it'll delete the invocation or in bot usage. Then it'll put it in an embed and add up and down vote reactions. Or maybe even do it so that you just send the suggestion in the channel without a command and it will delete it and do the above

**Comment by JohnnyJTH** [comment]
> Well isn't it just a command (+suggest), you'll execute it in either the channel itself and it'll delete the invocation or in bot usage. Then it'll put it in an embed and add up and down vote reactions. Or maybe even do it so that you just send the suggestion in the channel without a command and it will delete it and do the above

That would force people to use the discussion channel for example. Problem with that would be people who don't know it send there and the bot would make it a suggestion so maybe not a good idea

**Comment by parafoxia** [comment]
That's the sort of thing I had in mind, yeah. There's nothing to say that's what helish is thinking though. 😆

**Comment by helish88** [comment]
I have good idea, I think

**Comment by JohnnyJTH** [comment]
Please share it lol

**Comment by helish88** [comment]
so,
```py
@commands.command(aliases=["idea"])
@commands.cooldown(1, 30, commands.BucketType.member)
async def feedback(self, ctx, *, text: str=None):
    await ctx.message.delete()
    if not text:
        return await ctx.send(embed=discord.Embed(color=discord.Color.red(), title="You have not specified idea"))
    channel = self.bot.get_channel(626609252860952614)
    embed = discord.Embed(color=ctx.author.top_role.color,
                          description=f"user {ctx.author.display_name} suggests:", description=text)
    embed.set_footer(
        text=f"👍 - a good idea\n👎 - bad idea\n❗ - It is already on the server\n✅ - idea accepted\n❌ - idea rejected")
    message = await channel.send(embed=embed)
    await message.add_reaction('👍')
    await message.add_reaction('👎')

@idea.error
async def idea_error(self, ctx, error):
    if isinstance(error, commands.CommandOnCooldown):
        await ctx.message.delete()
        await ctx.send(embed=discord.Embed(color=discord.Color.red(),
                                           description=f'{ctx.author.mention} you will be able to use this command in  {error.retry_after:.1f} seconds'),
                       delete_after=20)```

**Comment by JohnnyJTH** [comment]
Yep I like that the mods can add like already added and accepted etc. Of course would need to limit others' perms to only add add to existing reactions, or make the bot detect it. Maybe add a accept reject command, so that the embed is not so big right off the bat.

**Comment by helish88** [comment]
2 solutions
1. Mods or Carberra will react with ✅ the idea is accepted or ❌ -  idea rejected
2. Add two commands, accept, reject
like accep suggest_id(idk) and comment, get the message, edit the embed adding footer for example
same with reject command

**Comment by JohnnyJTH** [comment]
Yup. That's what I meant. Personally I like the two command solution more, it would look better too. But it would make the whole thing much more complicated. Depends on what you other guys think.
