### ISSUE TITLE
Add duckduckgo command to sit alongside Google command

### ISSUE THREAD

**Issue by parafoxia** [Carberra/Carberretta#104]
Basically the same as `+google`, but with DDG instead.

In future btw @helish88, please open an issue before submitting a PR. I'll assign you to this if you comment on it.

**Comment by Nereg** [comment]
Do I need to find analog of https://letmegooglethat.com/ for DDG or I can implement with direct links to DDG ?

**Comment by IkBenOlie5** [comment]
#101 already being done by helish

**Comment by Nereg** [comment]
My bad
