### ISSUE TITLE
Add Bump Reminders

### ISSUE THREAD

**Issue by JohnnyJTH** [Carberra/Carberretta#108]
Add a system that reminds people to dump whenever it is possible to. It would have it's own role that people would opt in to, if they want to help. It would ideally check for bump on the website too, which is possible. ([Source: Book](https://discord.com/channels/626608699942764544/700100911200075786/847935796475985930))

**Comment by IkBenOlie5** [comment]
Extends #107

**Comment by JohnnyJTH** [comment]
Here is some code for reference
https://github.com/phenom4n4n/phen-cogs/tree/master/disboardreminder
