### ISSUE TITLE
Experience System

### ISSUE THREAD

**Issue by mshaugh** [Carberra/Carberretta#11]
# Experience System

**Features**

* Exponential levelling sytem
* Commands to opt out of level up messages

**Comment by IkBenOlie5** [comment]
I can do this one, (do the level up msgs have to go in bot-usage1?)

**Comment by parafoxia** [comment]
I'd say probably the best way of doing it is an opt in, where the level up message goes away after a time. Might be one for further discussion.

**Comment by IkBenOlie5** [comment]
wdym with they go away after a time, that you'd need to refresh it after x amount of time to get the messages again or something else?

**Comment by parafoxia** [comment]
Using the `delete_after` keyword to delete the message shortly before it appears.

**Comment by IkBenOlie5** [comment]
okay, and does it need a ping or just member.display_name?

**Comment by parafoxia** [comment]
I'd be tempted to stick with the display name. Maybe a reply, but one that doesn't ping?

**Comment by IkBenOlie5** [comment]
ok, btw is there a variable in the config for the bot-usage channels?

**Comment by parafoxia** [comment]
Don't think so. I'll DM you on Discord -- we have a test server that might make this all easier.

**Comment by parafoxia** [comment]
Would this still be something people want?
