### ISSUE TITLE
Should the bot send some embed in available support channels? 

### ISSUE THREAD

**Issue by Nereg** [Carberra/Carberretta#113]
Maybe the bot should send some sort of embed in available support channels? Something like [this](https://prnt.sc/1e17qqa) on Python server? It may contain some tips on how to ask questions and maybe display which helpers are online ?

**Comment by IkBenOlie5** [comment]
Isn't that basically support-information

**Comment by parafoxia** [comment]
Messages of this nature were intentionally not implemented, especially in the form of the Python server's ones, which are utterly obscene in their length and clutter everything up massively.

With that being said, some unobtrusive additional information could be appended to the closing or time out message directing people to #support-information. I'll consider it for Support V2.
