### ISSUE TITLE
Replace necessary parts of Solaris' gateway functionality

### ISSUE THREAD

**Issue by parafoxia** [Carberra/Carberretta#117]
The server is switching over to Discord's rules and welcome screens following Solaris' deprecation. Carberretta, however, needs to take on some of the tasks Solaris handled.

- [x] Send welcome message on member join
- [x] Send goodbye message on member leave
- [x] Provide members with the Announcements and Alerts (Videos) roles*
- [x] Role react system that works around it
    - [x] #3 
    - [x] #2

*Specific roles may be changed following a planned review of the system, but for now we're just replicating Solaris' behaviour. Resultant changes of that review will be implements in v1.5.1 or v2.x.

**Comment by neonjonn** [comment]
Yeah I can wait until the hikari version is released and then create an issue about it

**Comment by parafoxia** [comment]
Closed by 0fa9cd8.
