### ISSUE TITLE
Anyone can add more reactions to a reaction role message

### ISSUE THREAD

**Issue by Nereg** [Carberra/Carberretta#118]
Anyone can add reactions to the message other than used to assign roles ([screenshot](https://prnt.sc/1qof2om))
just making sure carb doesn't forget about it.

**Comment by MrDogeBro** [comment]
This should just be as simple as not allowing reactions in that channel (like in the discord settings for that channel, not the bot) because that will prevent new reactions from being added but still allow people to add to reactions that are already there.

**Comment by parafoxia** [comment]
That's...actually a good point.

**Comment by parafoxia** [comment]
Yeah that worked lmao. Thanks Doge!
