### ISSUE TITLE
YT playlist command

### ISSUE THREAD

**Issue by Book-py** [Carberra/Carberretta#126]
Make a command (probably going to be in V2) which allows you to search for playlists on the YouTube channel

It would be similar to the `+yt search` command. Maybe make `+yt search` a group and have sub-commands for videos and a sub-command for playlists?

**Comment by Book-py** [comment]
I **might** be able to write a version of the command to use and make a pull request for it if you want.

If I do, should I make it in discord.py or for the rewrite in hikari + lightbulb?

**Comment by Book-py** [comment]
Ok, thanks. I will probably wait till it is already ported over if it is ok.

Can you please ping me in your server when it is ported please, so I can start working on it?

**Comment by parafoxia** [comment]
Sure. It might be a while -- not sure what order I'm gonna port stuff over in.

**Comment by parafoxia** [comment]
So just to clarify, you'll PR this into the `task/port-youtube` branch. I'll let you know if I merge beforehand.

You'll need to:

- [ ] Create a playlist directory similar to how the video directory is created
- [ ] Create a new `playlist` subgroup with `link` and `info` commands

I've taken some data redundancy initiatives to make it easier to create the directory and compile the options for the autocorrect, so those two tasks are all you should need to do. Beyond that, refer to DMs.

**Comment by parafoxia** [comment]
Update: the YouTube port was merged early, so PR directly into main.
