### ISSUE TITLE
Binify command is broken

### ISSUE THREAD

**Issue by Jonxslays** [Carberra/Carberretta#146]
The mystbin api moved to the api.mystb.in subdomain causing the command to 404 because the endpoint were using no longer exists.

**Comment by parafoxia** [comment]
As we discussed this will be fixed in V1 and also ported to V2.

For the V2 implementation, dyou think it would be worth having a plugin specifically for this stuff and including the ability to get paste data? If not, I'm not 100% sure what plugin it would be a part of.

**Comment by parafoxia** [comment]
Closed in #150.
