### ISSUE TITLE
New support V2 using forums

### ISSUE THREAD

**Issue by parafoxia** [Carberra/Carberretta#147]
See [the discussion in the server](https://discord.com/channels/626608699942764544/626609252860952614/1019645389261000774) for more information.

This issue is only concerned with tasks Carberretta would perform in this system. Most functionality would be handled by the nature of forum channels.

Possible tasks:

- [x] #48
- [x] #50
- [x] #60
- [x] #61
- [ ] Reimplementation of the `close` command

Additional ideas should be commented below. Accepted ideas will be edited into this issue text.

This is currently blocked by https://github.com/hikari-py/hikari/issues/1104.

**Comment by JohnnyJTH** [comment]
I don't know if this is obvious, but a `/solved` command, that locks the forum and potentially adds the `Solved ☑` tag to the forum post if we will have one.

**Comment by parafoxia** [comment]
> I don't know if this is obvious, but a `/solved` command, that locks the forum post and potentially adds the `Solved ☑` tag to the forum post if we will have one. 

Ah yes, forgot to add that in. I like that idea, though I'm not sure of the implementation. I'd have to consider if (1) a command is the only viable way of doing it, and (2) if it isn't, whether other ways are better.

I also feel like a timeout probably isn't necessary for this, and that the solved implementation should be the only way to close a case. What are your thoughts on that?

**Comment by JohnnyJTH** [comment]
Yeah definitely.. I don't think timeouts are necessary.

**Comment by Jonxslays** [comment]
Another cool thing could could be if the bot watches the forum and if no helper responds within 30 minutes bot pings the proper roles.

**Comment by parafoxia** [comment]
> Another cool thing could could be if the bot watches the forum and if no helper responds within 30 minutes bot pings the proper roles.

Hm... I'm not so sure about this. #48 is designed to make pinging available after 30 mins, though I think all helpers getting pinged every support case might get a bit annoying.

**Comment by Jonxslays** [comment]
I mean, I assume they're gonna ping us every support case anyways if we don't help. That's the point of that rule. Up to you though isn't a big deal really.

**Comment by parafoxia** [comment]
Generally speaking there are far more support cases where there are no pings than pings, at least nowadays. The 30 min was introduced as a spam prevention measure so helpers didn't get inundated with pings before anyone had a chance to check the channels themselves.
