### ISSUE TITLE
Implement RTFM to replace R.Danny

### ISSUE THREAD

**Issue by vicky5124** [Carberra/Carberretta#27]
R.Danny is not verified, which means it will be limited to a single shard, which can cause the bot to stop working in the tutorials guild.

A replacement will be required, along with the other functionality of the bot such as Tags and Starboard

**Comment by parafoxia** [comment]
See #17 for tags and #8 for the starboard, but yeah, a replacement for the current RTFM command would be good.

**Comment by nitsuga5124** [comment]
both were mentioned to put them in priority, because they are used extensively on R.Danny

**Comment by parafoxia** [comment]
Makes sense.

**Comment by parafoxia** [comment]
Closed in #140.
