### ISSUE TITLE
Add timed closes for cases

### ISSUE THREAD

**Issue by MrDogeBro** [Carberra/Carberretta#54]
Add the ability for a helper or mod to be able to add a close timer to a support case. This is similar to the timeout feature but it would allow the case to actually close instead of timing out. If the user responded after setting the close timer it would stop the timer and not close the case, else it would be closed after the set amount of time.

The ability to do this would allow a helper to not have to close a case immediately while still being able to go help another case without having to remember to come back and close this case in `x` mins. This is not a necessity but would be a nice feature to have when helping people out in support cases.

### Example
* I give a user a solution that should work but want to give them time to ask more questions if they need or it doesn't seem to work. The timed close would allow the helper to say close the case in 10 mins if the person who opened the case does not respond. This allows the helper to know that the case will be fully closed because in 10 mins (or however long the helper sets) they would have responded if they had any issues but they did not, meaning the case can be closed as it is deemed solved.

### Features
* Add ability for helper to close case in `x` mins
* Allow client to respond to stop timer
* Make notification in chat that timer has been stopped and case re-opened (or something like that)
* Ping helper who time closed case if client responds (possibly — maybe in same message as above)

**Comment by parafoxia** [comment]
This will probably come in the form of a separate `+closein` command (unless someone has a better name for it) that takes a number of minutes as it's first and only argument.

- Restrict to staff (maybe only to participants of the case thus far)
- When cancelled, return to previous timeout method
- Allow ability to set timeout longer than 60 mins?
- Perhaps delete messages when timer is cancelled to stop it from cluttering as I imagine otherwise it could get pretty messy

**Comment by MrDogeBro** [comment]
You could just add it as an extra argument to the `+close` command that would be in the form of an int. It would just have to be an optional argument so that if you wanted to close the case right away it would be `+close` but if you wanted to close in 10 mins it would just be `+close 10`. I don't see the point in creating a second command for this but if there is a good reason I can understand that. That is just my opinion on the subject.

**Comment by parafoxia** [comment]
I'm reluctant to do it that way because the logic would be entirely different but I'll have a better think about it when I go to write it.

**Comment by mshaugh** [comment]
I agree, the optional time argument would be the preferred implementation.

- Separate the current close logic out of the command
- If argument given, schedule closure
- Otherwise, close now
