### ISSUE TITLE
User-Lookouts

### ISSUE THREAD

**Issue by TKelsier** [Carberra/Carberretta#58]
Add a command to add a person to a user-lookouts database.  This database would most likely include their username (of course) and the reason as to why they should be looked out for.  Each time a person joins the server, the bot will look to see if they are on the lookouts list and a notification message will be sent to one of the moderator channels.  Also add a command to check the entire server's members against the database to see if someone who is already joined is on the list. Of course add support to remove users from the list, however, I do not think this list should be open to the public like the warns system. A person should not be able to see if they are on the lookout list and nothing special will happen to a person who joins if they are on the list.

**Comment by parafoxia** [comment]
I agree with the implementation here, including the extra privacy over warns.

I propose the following implementation of commands:
- `+lookout add` adds a user to the db
- `+lookout rm|remove` to remove them
- `+lookout show` to show information on a particular user in the database
- `+lookout list` to list all members in the database
