### ISSUE TITLE
A system to bind a member bot to its owner

### ISSUE THREAD

**Issue by parafoxia** [Carberra/Carberretta#62]
- Probably `+bind` or `+bindbot`.
- Carberretta would update the bot nickname based on nickname changes of it's owner (and hopefully a username change in the bot)
- Carberretta would kick a bot if its owner left
- Would provide a simpler interface to determine bot owner info. Maybe `+memberbotinfo` or something (probably shorter than that)

**Comment by JohnnyJTH** [comment]
I can do it after logging
